# Generated by Django 3.1.2 on 2020-11-15 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20201115_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contest', to=settings.AUTH_USER_MODEL),
        ),
    ]
