# Generated by Django 3.1.2 on 2020-11-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Organization', 'Organization'), ('Individual', 'Individual')], default='Individual', max_length=240),
        ),
    ]
