# Generated by Django 3.1.2 on 2020-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='especiality_area',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Design', 'Design'), ('Sales', 'Sales')], max_length=240, null=True),
        ),
    ]
