# Generated by Django 3.1.2 on 2020-11-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
